In [57]:
import pandas as pd

In [58]:
atletico = pd.read_html("https://en.wikipedia.org/wiki/2021_Clube_Atl%C3%A9tico_Mineiro_season")

In [59]:
atletico[45]

,0,1,2,3,4
0,30 May 1,Atlético Mineiro,1–2,Fortaleza,Belo Horizonte
1,11:00 UTC−3,Hulk 40' (pen.),Report,"Yago Pikachu 60', 90+4'",Stadium: MineirãoAttendance: 0Referee: Caio Max Augusto Vieira

In [60]:
time1 = atletico[82][1][0]
placar = atletico[82][2][0]
time2 = atletico[82][3][0]
resultado = time1 + placar  +time2
resultado

'Grêmio4–3Atlético Mineiro'

In [61]:
df= pd.DataFrame()
for i in range(45,83):
    time1 = atletico[i][1][0]
    resultado = atletico[i][2][0]
    time2 = atletico[i][3][0]
    row = pd.Series([time1,resultado,time2])
    row_df = pd.DataFrame([row])
    df = pd.concat([row_df, df], ignore_index=True)

In [62]:

#mudar o nome das colunas
df.columns= ["time1","resultado","time2"]
df

                   time1 resultado                 time2
0                 Grêmio       4–3      Atlético Mineiro
1       Atlético Mineiro       4–3   Red Bull Bragantino
2                  Bahia       2–3      Atlético Mineiro
3       Atlético Mineiro       2–1            Fluminense
4              Palmeiras       2–2      Atlético Mineiro
5       Atlético Mineiro       2–0             Juventude
6   Athletico Paranaense       0–1      Atlético Mineiro
7       Atlético Mineiro       3–0           Corinthians
8       Atlético Mineiro       1–0       América Mineiro
9       Atlético Mineiro       2–1                Grêmio
10              Flamengo       1–0      Atlético Mineiro
11      Atlético Mineiro       2–1                Cuiabá
12   Atlético Goianiense       2–1      Atlético Mineiro
13      Atlético Mineiro       3–1                Santos
14      Atlético Mineiro       3–1                 Ceará
15           Chapecoense       2–2      Atlético Mineiro
16      Atlético Mineiro       1–0         Internacional
17             São Paulo       0–0      Atlético Mineiro
18      Atlético Mineiro       3–0                 Sport
19             Fortaleza       0–2      Atlético Mineiro
20   Red Bull Bragantino       1–1      Atlético Mineiro
21            Fluminense       1–1      Atlético Mineiro
22      Atlético Mineiro       2–0             Palmeiras
23             Juventude       1–2      Atlético Mineiro
24      Atlético Mineiro       2–0  Athletico Paranaense
25      Atlético Mineiro       3–0                 Bahia
26           Corinhtians       1–2      Atlético Mineiro
27       América Mineiro       0–1      Atlético Mineiro
28      Atlético Mineiro       2–1              Flamengo
29                Cuiabá       0–1      Atlético Mineiro
30      Atlético Mineiro       4–1   Atlético Goianiense
31                Santos       2–0      Atlético Mineiro
32                 Ceará       2–1      Atlético Mineiro
33      Atlético Mineiro       1–1           Chapecoense
34         Internacional       0–1      Atlético Mineiro
35      Atlético Mineiro       1–0             São Paulo
36                 Sport       0–1      Atlético Mineiro
37      Atlético Mineiro       1–2             Fortaleza

In [63]:
#separar em duas colunas
new = df["resultado"].str.split("–", n=1, expand=True)
df["Home"] = new[0]
df["Away"] = new[1]
df

                   time1 resultado                 time2 Home Away
0                 Grêmio       4–3      Atlético Mineiro    4    3
1       Atlético Mineiro       4–3   Red Bull Bragantino    4    3
2                  Bahia       2–3      Atlético Mineiro    2    3
3       Atlético Mineiro       2–1            Fluminense    2    1
4              Palmeiras       2–2      Atlético Mineiro    2    2
5       Atlético Mineiro       2–0             Juventude    2    0
6   Athletico Paranaense       0–1      Atlético Mineiro    0    1
7       Atlético Mineiro       3–0           Corinthians    3    0
8       Atlético Mineiro       1–0       América Mineiro    1    0
9       Atlético Mineiro       2–1                Grêmio    2    1
10              Flamengo       1–0      Atlético Mineiro    1    0
11      Atlético Mineiro       2–1                Cuiabá    2    1
12   Atlético Goianiense       2–1      Atlético Mineiro    2    1
13      Atlético Mineiro       3–1                Santos    3    1
14      Atlético Mineiro       3–1                 Ceará    3    1
15           Chapecoense       2–2      Atlético Mineiro    2    2
16      Atlético Mineiro       1–0         Internacional    1    0
17             São Paulo       0–0      Atlético Mineiro    0    0
18      Atlético Mineiro       3–0                 Sport    3    0
19             Fortaleza       0–2      Atlético Mineiro    0    2
20   Red Bull Bragantino       1–1      Atlético Mineiro    1    1
21            Fluminense       1–1      Atlético Mineiro    1    1
22      Atlético Mineiro       2–0             Palmeiras    2    0
23             Juventude       1–2      Atlético Mineiro    1    2
24      Atlético Mineiro       2–0  Athletico Paranaense    2    0
25      Atlético Mineiro       3–0                 Bahia    3    0
26           Corinhtians       1–2      Atlético Mineiro    1    2
27       América Mineiro       0–1      Atlético Mineiro    0    1
28      Atlético Mineiro       2–1              Flamengo    2    1
29                Cuiabá       0–1      Atlético Mineiro    0    1
30      Atlético Mineiro       4–1   Atlético Goianiense    4    1
31                Santos       2–0      Atlético Mineiro    2    0
32                 Ceará       2–1      Atlético Mineiro    2    1
33      Atlético Mineiro       1–1           Chapecoense    1    1
34         Internacional       0–1      Atlético Mineiro    0    1
35      Atlético Mineiro       1–0             São Paulo    1    0
36                 Sport       0–1      Atlético Mineiro    0    1
37      Atlético Mineiro       1–2             Fortaleza    1    2

In [64]:
import numpy as np

In [65]:
#Cria colunas de gols pro e gols contra
df['pro'] = np.where(df['time1']== 'Atlético Mineiro', df["Home"], df["Away"])
df['contra'] = np.where(df['time1']!= 'Atlético Mineiro', df["Home"], df["Away"])

In [66]:
df

                   time1 resultado                 time2 Home Away pro contra
0                 Grêmio       4–3      Atlético Mineiro    4    3   3      4
1       Atlético Mineiro       4–3   Red Bull Bragantino    4    3   4      3
2                  Bahia       2–3      Atlético Mineiro    2    3   3      2
3       Atlético Mineiro       2–1            Fluminense    2    1   2      1
4              Palmeiras       2–2      Atlético Mineiro    2    2   2      2
5       Atlético Mineiro       2–0             Juventude    2    0   2      0
6   Athletico Paranaense       0–1      Atlético Mineiro    0    1   1      0
7       Atlético Mineiro       3–0           Corinthians    3    0   3      0
8       Atlético Mineiro       1–0       América Mineiro    1    0   1      0
9       Atlético Mineiro       2–1                Grêmio    2    1   2      1
10              Flamengo       1–0      Atlético Mineiro    1    0   0      1
11      Atlético Mineiro       2–1                Cuiabá    2    1   2      1
12   Atlético Goianiense       2–1      Atlético Mineiro    2    1   1      2
13      Atlético Mineiro       3–1                Santos    3    1   3      1
14      Atlético Mineiro       3–1                 Ceará    3    1   3      1
15           Chapecoense       2–2      Atlético Mineiro    2    2   2      2
16      Atlético Mineiro       1–0         Internacional    1    0   1      0
17             São Paulo       0–0      Atlético Mineiro    0    0   0      0
18      Atlético Mineiro       3–0                 Sport    3    0   3      0
19             Fortaleza       0–2      Atlético Mineiro    0    2   2      0
20   Red Bull Bragantino       1–1      Atlético Mineiro    1    1   1      1
21            Fluminense       1–1      Atlético Mineiro    1    1   1      1
22      Atlético Mineiro       2–0             Palmeiras    2    0   2      0
23             Juventude       1–2      Atlético Mineiro    1    2   2      1
24      Atlético Mineiro       2–0  Athletico Paranaense    2    0   2      0
25      Atlético Mineiro       3–0                 Bahia    3    0   3      0
26           Corinhtians       1–2      Atlético Mineiro    1    2   2      1
27       América Mineiro       0–1      Atlético Mineiro    0    1   1      0
28      Atlético Mineiro       2–1              Flamengo    2    1   2      1
29                Cuiabá       0–1      Atlético Mineiro    0    1   1      0
30      Atlético Mineiro       4–1   Atlético Goianiense    4    1   4      1
31                Santos       2–0      Atlético Mineiro    2    0   0      2
32                 Ceará       2–1      Atlético Mineiro    2    1   1      2
33      Atlético Mineiro       1–1           Chapecoense    1    1   1      1
34         Internacional       0–1      Atlético Mineiro    0    1   1      0
35      Atlético Mineiro       1–0             São Paulo    1    0   1      0
36                 Sport       0–1      Atlético Mineiro    0    1   1      0
37      Atlético Mineiro       1–2             Fortaleza    1    2   1      2

In [67]:
df.to_csv("atletico.csv", sep='\t', encoding='utf-8')